spring.application.name=employee
# MongoDB Connection Configuration
spring.data.mongodb.uri=mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=6000&appName=mongosh+2.3.7

# Optional: Customizing MongoDB properties
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=employee
server.port=8081